main:
  project_name: week_08_example_04
  experiment_name: dev
data:
  train_data: "week_08_data_segregation/train_data.csv:latest"
decision_tree_pipeline:
  decision_tree:
    criterion: "entropy"
    splitter: "best"
    max_depth: null
  numerical_pipe:
    model: 0
  export_artifact: "null"