name: download_data_eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.3
  - seaborn=0.11.2
  - pandas=1.4.3
  - pip=22.1.2
  - matplotlib=3.5.2
  - pandas-profiling=3.2.0
  - scikit-learn=1.1.1
  - ipywidgets=7.7.1
  - jupyterlab_widgets=1.0.2
  - pip:
      - wandb==0.12.18