name: decision_tree_component
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.3
  - pip=22.1.2
  - matplotlib==3.2.2
  - pillow=8.4.0
  - scikit-learn=1.0.2
  - pip:
      - wandb==0.12.18
      - mlflow==1.26.1
      - omegaconf==2.2.2